Repository dnd-side-project/dnd-5th-3-backend, pull requests merged in 2021-09, with the labels that each got.

#97 Bugfix/#096 post list api
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
Labels: bug, fix

#99 [#98] fix: 이모지 추가한 member 삭제 안되는 오류 수정
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentEmojiMemberRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/EmojiService.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/EmojiServiceTest.java
Labels: fix

#102 Bugfix/#101 member withdrawal fix
  src/main/java/com/dnd5th3/dnd5th3backend/Dnd5th3BackendApplication.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomUserDetailServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/MemberType.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/member/MemberRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/scheduler/MemberScheduler.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
Labels: fix

#104 Feature/#103 admin
  build.gradle
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/SecurityConfig.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/member/MemberListResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/view/AdminViewController.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Role.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/resources/application-h2.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/members.html
  src/main/resources/templates/admin/posts.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/mail.html
Labels: enhancement

#106 Bugfix/#105 social account fix
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomAuthenticationProvider.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomUserDetailServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/oauth2/CustomOAuth2UserServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/scheduler/MemberScheduler.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/RandomNumber.java
Labels: bug

#109 [#108] feat: 소셜계정 check api 추가
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
Labels: enhancement

#111 Feature/#110 post delete api
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/exception/NoAuthorizationException.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: fix

#112 [#107] fix: mysql 버전 변경으로 create-drop 처리
  src/main/resources/application-dev.yml
Labels: fix

#113 Bugfix/#107 nickname dup fix
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/SecurityConfig.java
  src/main/resources/application-dev.yml
Labels: fix

#117 Feature#114 logging fix
  Dockerfile
  src/main/resources/application-dev.yml
  src/main/resources/logback-config.xml
Labels: fix

#119 Feature/#114 logging
  src/main/resources/application-dev.yml
  src/main/resources/logback-config.xml
Labels: fix

#124 Bugfix/#116 duplicate votes
  src/main/java/com/dnd5th3/dnd5th3backend/exception/DuplicateVoteException.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/VoteService.java
Labels: bug, fix
