Repository dnd-side-project/dnd-5th-3-backend, pull requests merged in 2021-08, with the labels that each got.

#18 Feature/#011 post api save
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/SecurityConfig.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/SaveRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/SaveResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/common/BaseTime.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/PostRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostService.java
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/utils/ApiDocumentUtils.java
Labels: enhancement

#20 Feature/#013 post api view
  build.gradle
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/common/BaseTime.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/exception/PostNotFoundException.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: enhancement

#21 Feature/#012 post api update
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/CalculateRatioDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/DeleteResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/UpdateRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: enhancement

#22 Feature/#017 comments save api
  src/docs/asciidoc/comments.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/CommentController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/exception/ErrorCode.java
  src/main/java/com/dnd5th3/dnd5th3backend/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/CommentRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentServiceImpl.java
  src/main/resources/static/docs/comments.html
  src/test/java/com/dnd5th3/dnd5th3backend/config/MockSecurityFilter.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
Labels: enhancement

#26 Feature/#014 post api list
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/AllResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostsListDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/PostsRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryCustom.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: enhancement

#28 Feature/#024 comment edit delete api
  src/docs/asciidoc/comments.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/CommentController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/static/docs/comments.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
Labels: enhancement

#29 Feature/#027 post api fix
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: fix

#31 Feature/#027 post api fix
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/SaveRequestDto.java
  src/main/resources/static/docs/comments.html
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
Labels: fix

#35 [Feature] vote 엔티티 생성
  src/main/java/com/dnd5th3/dnd5th3backend/domain/vote/Vote.java
Labels: enhancement

#36 Feature/#033 vote api
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/Dnd5th3BackendApplication.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomUserDetailServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/oauth2/CustomOAuth2UserServiceImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/DeleteResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/IdResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/VoteRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/vote/Vote.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/vote/VoteType.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/member/MemberRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryCustom.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/vote/VoteRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/vote/VoteRepositoryCustom.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/vote/VoteRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/VoteService.java
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/PostsRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/repository/VoteRepositoryTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/VoteServiceTest.java
Labels: enhancement

#42 Feature/#039 post api fix
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/CalculateRatioDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/vo/VoteRatioVo.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/VoteServiceTest.java
Labels: fix

#47 Feature/#044 post api mainpage
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/MainPostDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryCustom.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/RandomNumber.java
  src/main/resources/static/docs/comment.html
  src/main/resources/static/docs/emoji.html
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/VoteServiceTest.java
Labels: enhancement

#48 Feature/#046 post fix
  src/docs/asciidoc/posts.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/SaveRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/UpdateRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/VoteServiceTest.java
  src/test/resources/data-h2.sql
Labels: fix

#50 Bugfix/#049 comment get mod
  src/docs/asciidoc/comment.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/CommentController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentListResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentRepositoryCustomImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/vote/VoteRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
  src/test/java/http/login.http
  src/test/resources/data-h2.sql
Labels: fix

#52 Bugfix/#051 requests
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentListResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentResponseDto.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: fix

#55 Feature/#053 post api fix
  src/main/java/com/dnd5th3/dnd5th3backend/config/AmazonS3Config.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/MainPostDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/post/PostsListDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryCustom.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/S3Uploader.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
Labels: fix

#60 Feature/#059 post api fix
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
Labels: fix

#61 [#58] fix: comment reqeust에서 order group 정보 제거 및 대댓글 save API 추가
  src/docs/asciidoc/comment.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/CommentController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentListResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentRequestDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
  src/test/java/http/login.http
  src/test/resources/data-h2.sql
Labels: fix

#62 [#57] fix: refresh token 두번 생성하는 부분 수정
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomAuthenticationProvider.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/CustomAuthenticationToken.java
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/jwt/JwtTokenProvider.java
Labels: fix

#63 [#56] feat: 이메일, 닉네임 중복 확인 API 추가
  src/docs/asciidoc/member.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/SecurityConfig.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/member/MemberRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/test/java/com/dnd5th3/dnd5th3backend/config/TestConfig.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/MemberControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
Labels: enhancement

#65 [Fix] 게시글 삭제 api 수정
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
Labels: fix

#67 Bugfix/#066 comment count
  src/main/java/com/dnd5th3/dnd5th3backend/repository/comment/CommentRepository.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/resources/application-h2.yml
  src/main/resources/application-local.yml
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
Labels: fix

#69 Bugfix/#068 emoji checked
  src/main/java/com/dnd5th3/dnd5th3backend/controller/CommentController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/dto/comment/CommentListResponseDto.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/CommentEmoji.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/CommentService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/EmojiService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/CommentControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/CommentServiceTest.java
Labels: fix

#71 Feature/#070 member update api
  src/docs/asciidoc/member.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/CommentEmoji.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/MemberControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
  src/test/resources/data-h2.sql
Labels: enhancement

#78 Feature/#076 post fix mainpage
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/static/docs/comment.html
  src/main/resources/static/docs/member.html
  src/main/resources/static/docs/posts.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/MemberControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/PostsControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/PostsServiceTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/VoteServiceTest.java
  src/test/resources/data-h2.sql
Labels: fix

#80 Feature/#079 post list fix
  src/main/java/com/dnd5th3/dnd5th3backend/repository/posts/PostsRepositoryImpl.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/static/docs/comment.html
  src/main/resources/static/docs/emoji.html
  src/main/resources/static/docs/member.html
  src/main/resources/static/docs/posts.html
Labels: fix

#81 Feature/#077 member withdrawal
  src/docs/asciidoc/member.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/comment/Comment.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/posts/Posts.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/WtbUtil.java
  src/test/java/com/dnd5th3/dnd5th3backend/controller/MemberControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
Labels: enhancement

#90 Bugfix/#089 post list api
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
Labels: fix

#91 Bugfix/#089 post list api
  src/main/resources/application-dev.yml
Labels: fix

#92 Bugfix/#089 post list api
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/resources/application-dev.yml
Labels: wontfix

#83 Feature/#072 mail
  build.gradle
  src/docs/asciidoc/member.adoc
  src/main/java/com/dnd5th3/dnd5th3backend/config/security/SecurityConfig.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MemberController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/MyPageController.java
  src/main/java/com/dnd5th3/dnd5th3backend/controller/PostsController.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
  src/main/java/com/dnd5th3/dnd5th3backend/domain/vote/vo/VoteRatioVo.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/MemberService.java
  src/main/java/com/dnd5th3/dnd5th3backend/service/PostsService.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/EmailSender.java
  src/main/java/com/dnd5th3/dnd5th3backend/utils/RandomNumber.java
  src/main/resources/application.yml
  src/main/resources/templates/mail.html
  src/test/java/com/dnd5th3/dnd5th3backend/controller/MemberControllerTest.java
  src/test/java/com/dnd5th3/dnd5th3backend/service/MemberServiceTest.java
  src/test/resources/data-h2.sql
Labels: enhancement

#95 Feature/#094 member domain fix
  src/main/java/com/dnd5th3/dnd5th3backend/domain/member/Member.java
Labels: fix
